// Code generated by go-swagger; DO NOT EDIT.

package acl

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// ACLReadReader is a Reader for the ACLRead structure.
type ACLReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ACLReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewACLReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewACLReadOK creates a ACLReadOK with default headers values
func NewACLReadOK() *ACLReadOK {
	return &ACLReadOK{}
}

/* ACLReadOK describes a response with status code 200, with default header values.

GET operation response
*/
type ACLReadOK struct {
	Payload *models.ConfigReadACLResponse
}

func (o *ACLReadOK) Error() string {
	return fmt.Sprintf("[GET /dns/acl/{id}][%d] aclReadOK  %+v", 200, o.Payload)
}
func (o *ACLReadOK) GetPayload() *models.ConfigReadACLResponse {
	return o.Payload
}

func (o *ACLReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConfigReadACLResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
