// Code generated by go-swagger; DO NOT EDIT.

package option_space

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// OptionSpaceReadReader is a Reader for the OptionSpaceRead structure.
type OptionSpaceReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OptionSpaceReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOptionSpaceReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewOptionSpaceReadOK creates a OptionSpaceReadOK with default headers values
func NewOptionSpaceReadOK() *OptionSpaceReadOK {
	return &OptionSpaceReadOK{}
}

/* OptionSpaceReadOK describes a response with status code 200, with default header values.

GET operation response
*/
type OptionSpaceReadOK struct {
	Payload *models.IpamsvcReadOptionSpaceResponse
}

func (o *OptionSpaceReadOK) Error() string {
	return fmt.Sprintf("[GET /dhcp/option_space/{id}][%d] optionSpaceReadOK  %+v", 200, o.Payload)
}
func (o *OptionSpaceReadOK) GetPayload() *models.IpamsvcReadOptionSpaceResponse {
	return o.Payload
}

func (o *OptionSpaceReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcReadOptionSpaceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
