// Code generated by go-swagger; DO NOT EDIT.

package option_code

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// OptionCodeListReader is a Reader for the OptionCodeList structure.
type OptionCodeListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OptionCodeListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	if response.Code() >= 400 && response.Code() < 500 {
		return nil, runtime.NewAPIError("response status code indicates client error", response, response.Code())
	}

	if response.Code() >= 500 && response.Code() < 600 {
		return nil, runtime.NewAPIError("response status code indicates server error", response, response.Code())
	}

	result := NewOptionCodeListOK()
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	return result, nil
}

// NewOptionCodeListOK creates a OptionCodeListOK with default headers values
func NewOptionCodeListOK() *OptionCodeListOK {
	return &OptionCodeListOK{}
}

/* OptionCodeListOK describes a response with status code 200, with default header values.

GET operation response
*/
type OptionCodeListOK struct {
	Payload *models.IpamsvcListOptionCodeResponse
}

func (o *OptionCodeListOK) Error() string {
	return fmt.Sprintf("[GET /dhcp/option_code][%d] optionCodeListOK  %+v", 200, o.Payload)
}
func (o *OptionCodeListOK) GetPayload() *models.IpamsvcListOptionCodeResponse {
	return o.Payload
}

func (o *OptionCodeListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcListOptionCodeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
