// Code generated by go-swagger; DO NOT EDIT.

package option_code

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// OptionCodeReadReader is a Reader for the OptionCodeRead structure.
type OptionCodeReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OptionCodeReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOptionCodeReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewOptionCodeReadOK creates a OptionCodeReadOK with default headers values
func NewOptionCodeReadOK() *OptionCodeReadOK {
	return &OptionCodeReadOK{}
}

/* OptionCodeReadOK describes a response with status code 200, with default header values.

GET operation response
*/
type OptionCodeReadOK struct {
	Payload *models.IpamsvcReadOptionCodeResponse
}

func (o *OptionCodeReadOK) Error() string {
	return fmt.Sprintf("[GET /dhcp/option_code/{id}][%d] optionCodeReadOK  %+v", 200, o.Payload)
}
func (o *OptionCodeReadOK) GetPayload() *models.IpamsvcReadOptionCodeResponse {
	return o.Payload
}

func (o *OptionCodeReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcReadOptionCodeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
