// Code generated by go-swagger; DO NOT EDIT.

package option_code

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
	b1cliruntime "github.com/infobloxopen/b1ddi-go-client/runtime"
)

// OptionCodeCreateReader is a Reader for the OptionCodeCreate structure.
type OptionCodeCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OptionCodeCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	if response.Code() >= 400 && response.Code() < 500 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates client error", response.Body(), response.Code())
	}

	if response.Code() >= 500 && response.Code() < 600 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates server error", response.Body(), response.Code())
	}

	result := NewOptionCodeCreateOK()
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	return result, nil
}

// NewOptionCodeCreateOK creates a OptionCodeCreateOK with default headers values
func NewOptionCodeCreateOK() *OptionCodeCreateOK {
	return &OptionCodeCreateOK{}
}

/*
OptionCodeCreateOK describes a response with status code 200, with default header values.

POST operation response
*/
type OptionCodeCreateOK struct {
	Payload *models.IpamsvcCreateOptionCodeResponse
}

func (o *OptionCodeCreateOK) Error() string {
	return fmt.Sprintf("[POST /dhcp/option_code][%d] optionCodeCreateOK  %+v", 200, o.Payload)
}
func (o *OptionCodeCreateOK) GetPayload() *models.IpamsvcCreateOptionCodeResponse {
	return o.Payload
}

func (o *OptionCodeCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcCreateOptionCodeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
