// Code generated by go-swagger; DO NOT EDIT.

package global

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// GlobalRead2Reader is a Reader for the GlobalRead2 structure.
type GlobalRead2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GlobalRead2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGlobalRead2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGlobalRead2OK creates a GlobalRead2OK with default headers values
func NewGlobalRead2OK() *GlobalRead2OK {
	return &GlobalRead2OK{}
}

/* GlobalRead2OK describes a response with status code 200, with default header values.

GET operation response
*/
type GlobalRead2OK struct {
	Payload *models.IpamsvcReadGlobalResponse
}

func (o *GlobalRead2OK) Error() string {
	return fmt.Sprintf("[GET /dhcp/global/{id}][%d] globalRead2OK  %+v", 200, o.Payload)
}
func (o *GlobalRead2OK) GetPayload() *models.IpamsvcReadGlobalResponse {
	return o.Payload
}

func (o *GlobalRead2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcReadGlobalResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
