// Code generated by go-swagger; DO NOT EDIT.

package address

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// AddressListReader is a Reader for the AddressList structure.
type AddressListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddressListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddressListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddressListOK creates a AddressListOK with default headers values
func NewAddressListOK() *AddressListOK {
	return &AddressListOK{}
}

/* AddressListOK describes a response with status code 200, with default header values.

GET operation response
*/
type AddressListOK struct {
	Payload *models.IpamsvcListAddressResponse
}

func (o *AddressListOK) Error() string {
	return fmt.Sprintf("[GET /ipam/address][%d] addressListOK  %+v", 200, o.Payload)
}
func (o *AddressListOK) GetPayload() *models.IpamsvcListAddressResponse {
	return o.Payload
}

func (o *AddressListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcListAddressResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
