// Code generated by go-swagger; DO NOT EDIT.

package address

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AddressDeleteReader is a Reader for the AddressDelete structure.
type AddressDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddressDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewAddressDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddressDeleteNoContent creates a AddressDeleteNoContent with default headers values
func NewAddressDeleteNoContent() *AddressDeleteNoContent {
	return &AddressDeleteNoContent{}
}

/* AddressDeleteNoContent describes a response with status code 204, with default header values.

No Content
*/
type AddressDeleteNoContent struct {
}

func (o *AddressDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /ipam/address/{id}][%d] addressDeleteNoContent ", 204)
}

func (o *AddressDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
