// Code generated by go-swagger; DO NOT EDIT.

package ip_space

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
	b1cliruntime "github.com/infobloxopen/b1ddi-go-client/runtime"
)

// IPSpaceBulkCopyReader is a Reader for the IPSpaceBulkCopy structure.
type IPSpaceBulkCopyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IPSpaceBulkCopyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	if response.Code() >= 400 && response.Code() < 500 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates client error", response.Body(), response.Code())
	}

	if response.Code() >= 500 && response.Code() < 600 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates server error", response.Body(), response.Code())
	}

	result := NewIPSpaceBulkCopyOK()
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	return result, nil
}

// NewIPSpaceBulkCopyOK creates a IPSpaceBulkCopyOK with default headers values
func NewIPSpaceBulkCopyOK() *IPSpaceBulkCopyOK {
	return &IPSpaceBulkCopyOK{}
}

/*
IPSpaceBulkCopyOK describes a response with status code 200, with default header values.

POST operation response
*/
type IPSpaceBulkCopyOK struct {
	Payload *models.IpamsvcBulkCopyIPSpaceResponse
}

func (o *IPSpaceBulkCopyOK) Error() string {
	return fmt.Sprintf("[POST /ipam/ip_space/bulk_copy][%d] ipSpaceBulkCopyOK  %+v", 200, o.Payload)
}
func (o *IPSpaceBulkCopyOK) GetPayload() *models.IpamsvcBulkCopyIPSpaceResponse {
	return o.Payload
}

func (o *IPSpaceBulkCopyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcBulkCopyIPSpaceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
