// Code generated by go-swagger; DO NOT EDIT.

package ip_space

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// IPSpaceCreateReader is a Reader for the IPSpaceCreate structure.
type IPSpaceCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IPSpaceCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewIPSpaceCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewIPSpaceCreateCreated creates a IPSpaceCreateCreated with default headers values
func NewIPSpaceCreateCreated() *IPSpaceCreateCreated {
	return &IPSpaceCreateCreated{}
}

/* IPSpaceCreateCreated describes a response with status code 201, with default header values.

POST operation response
*/
type IPSpaceCreateCreated struct {
	Payload *models.IpamsvcCreateIPSpaceResponse
}

func (o *IPSpaceCreateCreated) Error() string {
	return fmt.Sprintf("[POST /ipam/ip_space][%d] ipSpaceCreateCreated  %+v", 201, o.Payload)
}
func (o *IPSpaceCreateCreated) GetPayload() *models.IpamsvcCreateIPSpaceResponse {
	return o.Payload
}

func (o *IPSpaceCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcCreateIPSpaceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
