// Code generated by go-swagger; DO NOT EDIT.

package ip_space

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// IPSpaceCopyReader is a Reader for the IPSpaceCopy structure.
type IPSpaceCopyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IPSpaceCopyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewIPSpaceCopyCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewIPSpaceCopyCreated creates a IPSpaceCopyCreated with default headers values
func NewIPSpaceCopyCreated() *IPSpaceCopyCreated {
	return &IPSpaceCopyCreated{}
}

/* IPSpaceCopyCreated describes a response with status code 201, with default header values.

POST operation response
*/
type IPSpaceCopyCreated struct {
	Payload *models.IpamsvcCopyIPSpaceResponse
}

func (o *IPSpaceCopyCreated) Error() string {
	return fmt.Sprintf("[POST /ipam/ip_space/{id}/copy][%d] ipSpaceCopyCreated  %+v", 201, o.Payload)
}
func (o *IPSpaceCopyCreated) GetPayload() *models.IpamsvcCopyIPSpaceResponse {
	return o.Payload
}

func (o *IPSpaceCopyCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcCopyIPSpaceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
