// Code generated by go-swagger; DO NOT EDIT.

package ip_space

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// IPSpaceUpdateReader is a Reader for the IPSpaceUpdate structure.
type IPSpaceUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IPSpaceUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewIPSpaceUpdateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewIPSpaceUpdateCreated creates a IPSpaceUpdateCreated with default headers values
func NewIPSpaceUpdateCreated() *IPSpaceUpdateCreated {
	return &IPSpaceUpdateCreated{}
}

/* IPSpaceUpdateCreated describes a response with status code 201, with default header values.

PATCH operation response
*/
type IPSpaceUpdateCreated struct {
	Payload *models.IpamsvcUpdateIPSpaceResponse
}

func (o *IPSpaceUpdateCreated) Error() string {
	return fmt.Sprintf("[PATCH /ipam/ip_space/{id}][%d] ipSpaceUpdateCreated  %+v", 201, o.Payload)
}
func (o *IPSpaceUpdateCreated) GetPayload() *models.IpamsvcUpdateIPSpaceResponse {
	return o.Payload
}

func (o *IPSpaceUpdateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcUpdateIPSpaceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
