// Code generated by go-swagger; DO NOT EDIT.

package ip_space

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	b1cliruntime "github.com/infobloxopen/b1ddi-go-client/runtime"
)

// IPSpaceDeleteReader is a Reader for the IPSpaceDelete structure.
type IPSpaceDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IPSpaceDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	if response.Code() >= 400 && response.Code() < 500 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates client error", response.Body(), response.Code())
	}

	if response.Code() >= 500 && response.Code() < 600 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates server error", response.Body(), response.Code())
	}

	result := NewIPSpaceDeleteOK()
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	return result, nil
}

// NewIPSpaceDeleteOK creates a IPSpaceDeleteOK with default headers values
func NewIPSpaceDeleteOK() *IPSpaceDeleteOK {
	return &IPSpaceDeleteOK{}
}

/*
IPSpaceDeleteOK describes a response with status code 200, with default header values.

OK
*/
type IPSpaceDeleteOK struct {
}

func (o *IPSpaceDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /ipam/ip_space/{id}][%d] ipSpaceDeleteOK ", 200)
}

func (o *IPSpaceDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
