// Code generated by go-swagger; DO NOT EDIT.

package ip_space

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// IPSpaceBulkCopyReader is a Reader for the IPSpaceBulkCopy structure.
type IPSpaceBulkCopyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IPSpaceBulkCopyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewIPSpaceBulkCopyCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewIPSpaceBulkCopyCreated creates a IPSpaceBulkCopyCreated with default headers values
func NewIPSpaceBulkCopyCreated() *IPSpaceBulkCopyCreated {
	return &IPSpaceBulkCopyCreated{}
}

/* IPSpaceBulkCopyCreated describes a response with status code 201, with default header values.

POST operation response
*/
type IPSpaceBulkCopyCreated struct {
	Payload *models.IpamsvcBulkCopyIPSpaceResponse
}

func (o *IPSpaceBulkCopyCreated) Error() string {
	return fmt.Sprintf("[POST /ipam/ip_space/bulk_copy][%d] ipSpaceBulkCopyCreated  %+v", 201, o.Payload)
}
func (o *IPSpaceBulkCopyCreated) GetPayload() *models.IpamsvcBulkCopyIPSpaceResponse {
	return o.Payload
}

func (o *IPSpaceBulkCopyCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcBulkCopyIPSpaceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
