// Code generated by go-swagger; DO NOT EDIT.

package ip_space

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
	b1cliruntime "github.com/infobloxopen/b1ddi-go-client/runtime"
)

// IPSpaceCopyReader is a Reader for the IPSpaceCopy structure.
type IPSpaceCopyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IPSpaceCopyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	if response.Code() >= 400 && response.Code() < 500 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates client error", response.Body(), response.Code())
	}

	if response.Code() >= 500 && response.Code() < 600 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates server error", response.Body(), response.Code())
	}

	result := NewIPSpaceCopyOK()
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	return result, nil
}

// NewIPSpaceCopyOK creates a IPSpaceCopyOK with default headers values
func NewIPSpaceCopyOK() *IPSpaceCopyOK {
	return &IPSpaceCopyOK{}
}

/*
IPSpaceCopyOK describes a response with status code 200, with default header values.

POST operation response
*/
type IPSpaceCopyOK struct {
	Payload *models.IpamsvcCopyIPSpaceResponse
}

func (o *IPSpaceCopyOK) Error() string {
	return fmt.Sprintf("[POST /ipam/ip_space/{id}/copy][%d] ipSpaceCopyOK  %+v", 200, o.Payload)
}
func (o *IPSpaceCopyOK) GetPayload() *models.IpamsvcCopyIPSpaceResponse {
	return o.Payload
}

func (o *IPSpaceCopyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcCopyIPSpaceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
