// Code generated by go-swagger; DO NOT EDIT.

package ip_space

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// IPSpaceReadReader is a Reader for the IPSpaceRead structure.
type IPSpaceReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IPSpaceReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIPSpaceReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewIPSpaceReadOK creates a IPSpaceReadOK with default headers values
func NewIPSpaceReadOK() *IPSpaceReadOK {
	return &IPSpaceReadOK{}
}

/* IPSpaceReadOK describes a response with status code 200, with default header values.

GET operation response
*/
type IPSpaceReadOK struct {
	Payload *models.IpamsvcReadIPSpaceResponse
}

func (o *IPSpaceReadOK) Error() string {
	return fmt.Sprintf("[GET /ipam/ip_space/{id}][%d] ipSpaceReadOK  %+v", 200, o.Payload)
}
func (o *IPSpaceReadOK) GetPayload() *models.IpamsvcReadIPSpaceResponse {
	return o.Payload
}

func (o *IPSpaceReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcReadIPSpaceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
