// Code generated by go-swagger; DO NOT EDIT.

package leases_command

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// NewLeasesCommandCreateParams creates a new LeasesCommandCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLeasesCommandCreateParams() *LeasesCommandCreateParams {
	return &LeasesCommandCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLeasesCommandCreateParamsWithTimeout creates a new LeasesCommandCreateParams object
// with the ability to set a timeout on a request.
func NewLeasesCommandCreateParamsWithTimeout(timeout time.Duration) *LeasesCommandCreateParams {
	return &LeasesCommandCreateParams{
		timeout: timeout,
	}
}

// NewLeasesCommandCreateParamsWithContext creates a new LeasesCommandCreateParams object
// with the ability to set a context for a request.
func NewLeasesCommandCreateParamsWithContext(ctx context.Context) *LeasesCommandCreateParams {
	return &LeasesCommandCreateParams{
		Context: ctx,
	}
}

// NewLeasesCommandCreateParamsWithHTTPClient creates a new LeasesCommandCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewLeasesCommandCreateParamsWithHTTPClient(client *http.Client) *LeasesCommandCreateParams {
	return &LeasesCommandCreateParams{
		HTTPClient: client,
	}
}

/*
LeasesCommandCreateParams contains all the parameters to send to the API endpoint

	for the leases command create operation.

	Typically these are written to a http.Request.
*/
type LeasesCommandCreateParams struct {

	// Body.
	Body *models.IpamsvcLeasesCommand

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the leases command create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LeasesCommandCreateParams) WithDefaults() *LeasesCommandCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the leases command create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LeasesCommandCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the leases command create params
func (o *LeasesCommandCreateParams) WithTimeout(timeout time.Duration) *LeasesCommandCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the leases command create params
func (o *LeasesCommandCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the leases command create params
func (o *LeasesCommandCreateParams) WithContext(ctx context.Context) *LeasesCommandCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the leases command create params
func (o *LeasesCommandCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the leases command create params
func (o *LeasesCommandCreateParams) WithHTTPClient(client *http.Client) *LeasesCommandCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the leases command create params
func (o *LeasesCommandCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the leases command create params
func (o *LeasesCommandCreateParams) WithBody(body *models.IpamsvcLeasesCommand) *LeasesCommandCreateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the leases command create params
func (o *LeasesCommandCreateParams) SetBody(body *models.IpamsvcLeasesCommand) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *LeasesCommandCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
