// Code generated by go-swagger; DO NOT EDIT.

package leases_command

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new leases command API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for leases command API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	LeasesCommandCreate(params *LeasesCommandCreateParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*LeasesCommandCreateCreated, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
	LeasesCommandCreate performs actions like clearing d h c p lease s

	Use this method to create a __LeasesCommand__ object.

The __LeasesCommand__ object (_dhcp/leases_command_) is used for performing an action like clearing DHCP lease(s).
*/
func (a *Client) LeasesCommandCreate(params *LeasesCommandCreateParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*LeasesCommandCreateCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewLeasesCommandCreateParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "leases_commandCreate",
		Method:             "POST",
		PathPattern:        "/dhcp/leases_command",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &LeasesCommandCreateReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*LeasesCommandCreateCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for leases_commandCreate: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
