// Code generated by go-swagger; DO NOT EDIT.

package ha_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	b1cliruntime "github.com/infobloxopen/b1ddi-go-client/runtime"
)

// HaGroupDeleteReader is a Reader for the HaGroupDelete structure.
type HaGroupDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HaGroupDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	if response.Code() >= 400 && response.Code() < 500 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates client error", response.Body(), response.Code())
	}

	if response.Code() >= 500 && response.Code() < 600 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates server error", response.Body(), response.Code())
	}

	result := NewHaGroupDeleteOK()
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	return result, nil
}

// NewHaGroupDeleteOK creates a HaGroupDeleteOK with default headers values
func NewHaGroupDeleteOK() *HaGroupDeleteOK {
	return &HaGroupDeleteOK{}
}

/*
HaGroupDeleteOK describes a response with status code 200, with default header values.

OK
*/
type HaGroupDeleteOK struct {
}

func (o *HaGroupDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /dhcp/ha_group/{id}][%d] haGroupDeleteOK ", 200)
}

func (o *HaGroupDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
