// Code generated by go-swagger; DO NOT EDIT.

package ha_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// HaGroupCreateReader is a Reader for the HaGroupCreate structure.
type HaGroupCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HaGroupCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewHaGroupCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewHaGroupCreateCreated creates a HaGroupCreateCreated with default headers values
func NewHaGroupCreateCreated() *HaGroupCreateCreated {
	return &HaGroupCreateCreated{}
}

/* HaGroupCreateCreated describes a response with status code 201, with default header values.

POST operation response
*/
type HaGroupCreateCreated struct {
	Payload *models.IpamsvcCreateHAGroupResponse
}

func (o *HaGroupCreateCreated) Error() string {
	return fmt.Sprintf("[POST /dhcp/ha_group][%d] haGroupCreateCreated  %+v", 201, o.Payload)
}
func (o *HaGroupCreateCreated) GetPayload() *models.IpamsvcCreateHAGroupResponse {
	return o.Payload
}

func (o *HaGroupCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcCreateHAGroupResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
