// Code generated by go-swagger; DO NOT EDIT.

package hardware_filter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
	b1cliruntime "github.com/infobloxopen/b1ddi-go-client/runtime"
)

// HardwareFilterCreateReader is a Reader for the HardwareFilterCreate structure.
type HardwareFilterCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HardwareFilterCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	if response.Code() >= 400 && response.Code() < 500 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates client error", response.Body(), response.Code())
	}

	if response.Code() >= 500 && response.Code() < 600 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates server error", response.Body(), response.Code())
	}

	result := NewHardwareFilterCreateOK()
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	return result, nil
}

// NewHardwareFilterCreateOK creates a HardwareFilterCreateOK with default headers values
func NewHardwareFilterCreateOK() *HardwareFilterCreateOK {
	return &HardwareFilterCreateOK{}
}

/*
HardwareFilterCreateOK describes a response with status code 200, with default header values.

POST operation response
*/
type HardwareFilterCreateOK struct {
	Payload *models.IpamsvcCreateHardwareFilterResponse
}

func (o *HardwareFilterCreateOK) Error() string {
	return fmt.Sprintf("[POST /dhcp/hardware_filter][%d] hardwareFilterCreateOK  %+v", 200, o.Payload)
}
func (o *HardwareFilterCreateOK) GetPayload() *models.IpamsvcCreateHardwareFilterResponse {
	return o.Payload
}

func (o *HardwareFilterCreateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcCreateHardwareFilterResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
