// Code generated by go-swagger; DO NOT EDIT.

package subnet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// SubnetReadReader is a Reader for the SubnetRead structure.
type SubnetReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SubnetReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSubnetReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSubnetReadOK creates a SubnetReadOK with default headers values
func NewSubnetReadOK() *SubnetReadOK {
	return &SubnetReadOK{}
}

/* SubnetReadOK describes a response with status code 200, with default header values.

GET operation response
*/
type SubnetReadOK struct {
	Payload *models.IpamsvcReadSubnetResponse
}

func (o *SubnetReadOK) Error() string {
	return fmt.Sprintf("[GET /ipam/subnet/{id}][%d] subnetReadOK  %+v", 200, o.Payload)
}
func (o *SubnetReadOK) GetPayload() *models.IpamsvcReadSubnetResponse {
	return o.Payload
}

func (o *SubnetReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcReadSubnetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
