// Code generated by go-swagger; DO NOT EDIT.

package forward_zone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// ForwardZoneCopyReader is a Reader for the ForwardZoneCopy structure.
type ForwardZoneCopyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ForwardZoneCopyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewForwardZoneCopyCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewForwardZoneCopyCreated creates a ForwardZoneCopyCreated with default headers values
func NewForwardZoneCopyCreated() *ForwardZoneCopyCreated {
	return &ForwardZoneCopyCreated{}
}

/* ForwardZoneCopyCreated describes a response with status code 201, with default header values.

POST operation response
*/
type ForwardZoneCopyCreated struct {
	Payload *models.ConfigCopyForwardZoneResponse
}

func (o *ForwardZoneCopyCreated) Error() string {
	return fmt.Sprintf("[POST /dns/forward_zone/copy][%d] forwardZoneCopyCreated  %+v", 201, o.Payload)
}
func (o *ForwardZoneCopyCreated) GetPayload() *models.ConfigCopyForwardZoneResponse {
	return o.Payload
}

func (o *ForwardZoneCopyCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConfigCopyForwardZoneResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
