// Code generated by go-swagger; DO NOT EDIT.

package forward_zone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// ForwardZoneListReader is a Reader for the ForwardZoneList structure.
type ForwardZoneListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ForwardZoneListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewForwardZoneListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewForwardZoneListOK creates a ForwardZoneListOK with default headers values
func NewForwardZoneListOK() *ForwardZoneListOK {
	return &ForwardZoneListOK{}
}

/* ForwardZoneListOK describes a response with status code 200, with default header values.

GET operation response
*/
type ForwardZoneListOK struct {
	Payload *models.ConfigListForwardZoneResponse
}

func (o *ForwardZoneListOK) Error() string {
	return fmt.Sprintf("[GET /dns/forward_zone][%d] forwardZoneListOK  %+v", 200, o.Payload)
}
func (o *ForwardZoneListOK) GetPayload() *models.ConfigListForwardZoneResponse {
	return o.Payload
}

func (o *ForwardZoneListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConfigListForwardZoneResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
