// Code generated by go-swagger; DO NOT EDIT.

package forward_zone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// ForwardZoneCreateReader is a Reader for the ForwardZoneCreate structure.
type ForwardZoneCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ForwardZoneCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewForwardZoneCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewForwardZoneCreateCreated creates a ForwardZoneCreateCreated with default headers values
func NewForwardZoneCreateCreated() *ForwardZoneCreateCreated {
	return &ForwardZoneCreateCreated{}
}

/* ForwardZoneCreateCreated describes a response with status code 201, with default header values.

POST operation response
*/
type ForwardZoneCreateCreated struct {
	Payload *models.ConfigCreateForwardZoneResponse
}

func (o *ForwardZoneCreateCreated) Error() string {
	return fmt.Sprintf("[POST /dns/forward_zone][%d] forwardZoneCreateCreated  %+v", 201, o.Payload)
}
func (o *ForwardZoneCreateCreated) GetPayload() *models.ConfigCreateForwardZoneResponse {
	return o.Payload
}

func (o *ForwardZoneCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConfigCreateForwardZoneResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
