// Code generated by go-swagger; DO NOT EDIT.

package auth_nsg

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	b1cliruntime "github.com/infobloxopen/b1ddi-go-client/runtime"
)

// AuthNsgDeleteReader is a Reader for the AuthNsgDelete structure.
type AuthNsgDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AuthNsgDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	if response.Code() >= 400 && response.Code() < 500 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates client error", response.Body(), response.Code())
	}

	if response.Code() >= 500 && response.Code() < 600 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates server error", response.Body(), response.Code())
	}

	result := NewAuthNsgDeleteOK()
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	return result, nil
}

// NewAuthNsgDeleteOK creates a AuthNsgDeleteOK with default headers values
func NewAuthNsgDeleteOK() *AuthNsgDeleteOK {
	return &AuthNsgDeleteOK{}
}

/*
AuthNsgDeleteOK describes a response with status code 200, with default header values.

OK
*/
type AuthNsgDeleteOK struct {
}

func (o *AuthNsgDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /dns/auth_nsg/{id}][%d] authNsgDeleteOK ", 200)
}

func (o *AuthNsgDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
