// Code generated by go-swagger; DO NOT EDIT.

package forward_nsg

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// ForwardNsgReadReader is a Reader for the ForwardNsgRead structure.
type ForwardNsgReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ForwardNsgReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewForwardNsgReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewForwardNsgReadOK creates a ForwardNsgReadOK with default headers values
func NewForwardNsgReadOK() *ForwardNsgReadOK {
	return &ForwardNsgReadOK{}
}

/* ForwardNsgReadOK describes a response with status code 200, with default header values.

GET operation response
*/
type ForwardNsgReadOK struct {
	Payload *models.ConfigReadForwardNSGResponse
}

func (o *ForwardNsgReadOK) Error() string {
	return fmt.Sprintf("[GET /dns/forward_nsg/{id}][%d] forwardNsgReadOK  %+v", 200, o.Payload)
}
func (o *ForwardNsgReadOK) GetPayload() *models.ConfigReadForwardNSGResponse {
	return o.Payload
}

func (o *ForwardNsgReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConfigReadForwardNSGResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
