// Code generated by go-swagger; DO NOT EDIT.

package forward_nsg

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ForwardNsgDeleteReader is a Reader for the ForwardNsgDelete structure.
type ForwardNsgDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ForwardNsgDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewForwardNsgDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewForwardNsgDeleteNoContent creates a ForwardNsgDeleteNoContent with default headers values
func NewForwardNsgDeleteNoContent() *ForwardNsgDeleteNoContent {
	return &ForwardNsgDeleteNoContent{}
}

/* ForwardNsgDeleteNoContent describes a response with status code 204, with default header values.

No Content
*/
type ForwardNsgDeleteNoContent struct {
}

func (o *ForwardNsgDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /dns/forward_nsg/{id}][%d] forwardNsgDeleteNoContent ", 204)
}

func (o *ForwardNsgDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
