// Code generated by go-swagger; DO NOT EDIT.

package asm

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// AsmReadReader is a Reader for the AsmRead structure.
type AsmReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AsmReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAsmReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAsmReadOK creates a AsmReadOK with default headers values
func NewAsmReadOK() *AsmReadOK {
	return &AsmReadOK{}
}

/* AsmReadOK describes a response with status code 200, with default header values.

GET operation response
*/
type AsmReadOK struct {
	Payload *models.IpamsvcReadASMResponse
}

func (o *AsmReadOK) Error() string {
	return fmt.Sprintf("[GET /ipam/asm/{id}][%d] asmReadOK  %+v", 200, o.Payload)
}
func (o *AsmReadOK) GetPayload() *models.IpamsvcReadASMResponse {
	return o.Payload
}

func (o *AsmReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcReadASMResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
