// Code generated by go-swagger; DO NOT EDIT.

package option_filter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// OptionFilterReadReader is a Reader for the OptionFilterRead structure.
type OptionFilterReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OptionFilterReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOptionFilterReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewOptionFilterReadOK creates a OptionFilterReadOK with default headers values
func NewOptionFilterReadOK() *OptionFilterReadOK {
	return &OptionFilterReadOK{}
}

/* OptionFilterReadOK describes a response with status code 200, with default header values.

GET operation response
*/
type OptionFilterReadOK struct {
	Payload *models.IpamsvcReadOptionFilterResponse
}

func (o *OptionFilterReadOK) Error() string {
	return fmt.Sprintf("[GET /dhcp/option_filter/{id}][%d] optionFilterReadOK  %+v", 200, o.Payload)
}
func (o *OptionFilterReadOK) GetPayload() *models.IpamsvcReadOptionFilterResponse {
	return o.Payload
}

func (o *OptionFilterReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcReadOptionFilterResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
