// Code generated by go-swagger; DO NOT EDIT.

package option_filter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// OptionFilterUpdateReader is a Reader for the OptionFilterUpdate structure.
type OptionFilterUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OptionFilterUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewOptionFilterUpdateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewOptionFilterUpdateCreated creates a OptionFilterUpdateCreated with default headers values
func NewOptionFilterUpdateCreated() *OptionFilterUpdateCreated {
	return &OptionFilterUpdateCreated{}
}

/* OptionFilterUpdateCreated describes a response with status code 201, with default header values.

PATCH operation response
*/
type OptionFilterUpdateCreated struct {
	Payload *models.IpamsvcUpdateOptionFilterResponse
}

func (o *OptionFilterUpdateCreated) Error() string {
	return fmt.Sprintf("[PATCH /dhcp/option_filter/{id}][%d] optionFilterUpdateCreated  %+v", 201, o.Payload)
}
func (o *OptionFilterUpdateCreated) GetPayload() *models.IpamsvcUpdateOptionFilterResponse {
	return o.Payload
}

func (o *OptionFilterUpdateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcUpdateOptionFilterResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
