// Code generated by go-swagger; DO NOT EDIT.

package option_filter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	b1cliruntime "github.com/infobloxopen/b1ddi-go-client/runtime"
)

// OptionFilterDeleteReader is a Reader for the OptionFilterDelete structure.
type OptionFilterDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OptionFilterDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	if response.Code() >= 400 && response.Code() < 500 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates client error", response.Body(), response.Code())
	}

	if response.Code() >= 500 && response.Code() < 600 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates server error", response.Body(), response.Code())
	}

	result := NewOptionFilterDeleteOK()
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	return result, nil
}

// NewOptionFilterDeleteOK creates a OptionFilterDeleteOK with default headers values
func NewOptionFilterDeleteOK() *OptionFilterDeleteOK {
	return &OptionFilterDeleteOK{}
}

/*
OptionFilterDeleteOK describes a response with status code 200, with default header values.

OK
*/
type OptionFilterDeleteOK struct {
}

func (o *OptionFilterDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /dhcp/option_filter/{id}][%d] optionFilterDeleteOK ", 200)
}

func (o *OptionFilterDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
