// Code generated by go-swagger; DO NOT EDIT.

package option_filter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// OptionFilterListReader is a Reader for the OptionFilterList structure.
type OptionFilterListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OptionFilterListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOptionFilterListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewOptionFilterListOK creates a OptionFilterListOK with default headers values
func NewOptionFilterListOK() *OptionFilterListOK {
	return &OptionFilterListOK{}
}

/* OptionFilterListOK describes a response with status code 200, with default header values.

GET operation response
*/
type OptionFilterListOK struct {
	Payload *models.IpamsvcListOptionFilterResponse
}

func (o *OptionFilterListOK) Error() string {
	return fmt.Sprintf("[GET /dhcp/option_filter][%d] optionFilterListOK  %+v", 200, o.Payload)
}
func (o *OptionFilterListOK) GetPayload() *models.IpamsvcListOptionFilterResponse {
	return o.Payload
}

func (o *OptionFilterListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcListOptionFilterResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
