// Code generated by go-swagger; DO NOT EDIT.

package option_filter

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
	b1cliruntime "github.com/infobloxopen/b1ddi-go-client/runtime"
)

// OptionFilterUpdateReader is a Reader for the OptionFilterUpdate structure.
type OptionFilterUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OptionFilterUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	if response.Code() >= 400 && response.Code() < 500 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates client error", response.Body(), response.Code())
	}

	if response.Code() >= 500 && response.Code() < 600 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates server error", response.Body(), response.Code())
	}

	result := NewOptionFilterUpdateOK()
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	return result, nil
}

// NewOptionFilterUpdateOK creates a OptionFilterUpdateOK with default headers values
func NewOptionFilterUpdateOK() *OptionFilterUpdateOK {
	return &OptionFilterUpdateOK{}
}

/*
OptionFilterUpdateOK describes a response with status code 200, with default header values.

PATCH operation response
*/
type OptionFilterUpdateOK struct {
	Payload *models.IpamsvcUpdateOptionFilterResponse
}

func (o *OptionFilterUpdateOK) Error() string {
	return fmt.Sprintf("[PATCH /dhcp/option_filter/{id}][%d] optionFilterUpdateOK  %+v", 200, o.Payload)
}
func (o *OptionFilterUpdateOK) GetPayload() *models.IpamsvcUpdateOptionFilterResponse {
	return o.Payload
}

func (o *OptionFilterUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcUpdateOptionFilterResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
