// Code generated by go-swagger; DO NOT EDIT.

package range_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// RangeDeleteReader is a Reader for the RangeDelete structure.
type RangeDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RangeDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewRangeDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRangeDeleteNoContent creates a RangeDeleteNoContent with default headers values
func NewRangeDeleteNoContent() *RangeDeleteNoContent {
	return &RangeDeleteNoContent{}
}

/* RangeDeleteNoContent describes a response with status code 204, with default header values.

No Content
*/
type RangeDeleteNoContent struct {
}

func (o *RangeDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /ipam/range/{id}][%d] rangeDeleteNoContent ", 204)
}

func (o *RangeDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
