// Code generated by go-swagger; DO NOT EDIT.

package range_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// RangeCreateNextAvailableIPReader is a Reader for the RangeCreateNextAvailableIP structure.
type RangeCreateNextAvailableIPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RangeCreateNextAvailableIPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewRangeCreateNextAvailableIPCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRangeCreateNextAvailableIPCreated creates a RangeCreateNextAvailableIPCreated with default headers values
func NewRangeCreateNextAvailableIPCreated() *RangeCreateNextAvailableIPCreated {
	return &RangeCreateNextAvailableIPCreated{}
}

/* RangeCreateNextAvailableIPCreated describes a response with status code 201, with default header values.

POST operation response
*/
type RangeCreateNextAvailableIPCreated struct {
	Payload *models.IpamsvcCreateNextAvailableIPResponse
}

func (o *RangeCreateNextAvailableIPCreated) Error() string {
	return fmt.Sprintf("[POST /ipam/range/{id}/nextavailableip][%d] rangeCreateNextAvailableIpCreated  %+v", 201, o.Payload)
}
func (o *RangeCreateNextAvailableIPCreated) GetPayload() *models.IpamsvcCreateNextAvailableIPResponse {
	return o.Payload
}

func (o *RangeCreateNextAvailableIPCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcCreateNextAvailableIPResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
