// Code generated by go-swagger; DO NOT EDIT.

package ipam_host

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// IpamHostDeleteReader is a Reader for the IpamHostDelete structure.
type IpamHostDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamHostDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewIpamHostDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewIpamHostDeleteNoContent creates a IpamHostDeleteNoContent with default headers values
func NewIpamHostDeleteNoContent() *IpamHostDeleteNoContent {
	return &IpamHostDeleteNoContent{}
}

/* IpamHostDeleteNoContent describes a response with status code 204, with default header values.

No Content
*/
type IpamHostDeleteNoContent struct {
}

func (o *IpamHostDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /ipam/host/{id}][%d] ipamHostDeleteNoContent ", 204)
}

func (o *IpamHostDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
