// Code generated by go-swagger; DO NOT EDIT.

package ipam_host

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// IpamHostReadReader is a Reader for the IpamHostRead structure.
type IpamHostReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IpamHostReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIpamHostReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewIpamHostReadOK creates a IpamHostReadOK with default headers values
func NewIpamHostReadOK() *IpamHostReadOK {
	return &IpamHostReadOK{}
}

/* IpamHostReadOK describes a response with status code 200, with default header values.

GET operation response
*/
type IpamHostReadOK struct {
	Payload *models.IpamsvcReadIpamHostResponse
}

func (o *IpamHostReadOK) Error() string {
	return fmt.Sprintf("[GET /ipam/host/{id}][%d] ipamHostReadOK  %+v", 200, o.Payload)
}
func (o *IpamHostReadOK) GetPayload() *models.IpamsvcReadIpamHostResponse {
	return o.Payload
}

func (o *IpamHostReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcReadIpamHostResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
