// Code generated by go-swagger; DO NOT EDIT.

package convert_domain_name

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// ConvertDomainNameConvertReader is a Reader for the ConvertDomainNameConvert structure.
type ConvertDomainNameConvertReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ConvertDomainNameConvertReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewConvertDomainNameConvertOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewConvertDomainNameConvertOK creates a ConvertDomainNameConvertOK with default headers values
func NewConvertDomainNameConvertOK() *ConvertDomainNameConvertOK {
	return &ConvertDomainNameConvertOK{}
}

/* ConvertDomainNameConvertOK describes a response with status code 200, with default header values.

GET operation response
*/
type ConvertDomainNameConvertOK struct {
	Payload *models.ConfigConvertDomainNameResponse
}

func (o *ConvertDomainNameConvertOK) Error() string {
	return fmt.Sprintf("[GET /dns/convert_domain_name/{domain_name}][%d] convertDomainNameConvertOK  %+v", 200, o.Payload)
}
func (o *ConvertDomainNameConvertOK) GetPayload() *models.ConfigConvertDomainNameResponse {
	return o.Payload
}

func (o *ConvertDomainNameConvertOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConfigConvertDomainNameResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
