// Code generated by go-swagger; DO NOT EDIT.

package dns_usage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// DNSUsageListReader is a Reader for the DNSUsageList structure.
type DNSUsageListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DNSUsageListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDNSUsageListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDNSUsageListOK creates a DNSUsageListOK with default headers values
func NewDNSUsageListOK() *DNSUsageListOK {
	return &DNSUsageListOK{}
}

/* DNSUsageListOK describes a response with status code 200, with default header values.

GET operation response
*/
type DNSUsageListOK struct {
	Payload *models.IpamsvcListDNSUsageResponse
}

func (o *DNSUsageListOK) Error() string {
	return fmt.Sprintf("[GET /ipam/dns_usage][%d] dnsUsageListOK  %+v", 200, o.Payload)
}
func (o *DNSUsageListOK) GetPayload() *models.IpamsvcListDNSUsageResponse {
	return o.Payload
}

func (o *DNSUsageListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcListDNSUsageResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
