// Code generated by go-swagger; DO NOT EDIT.

package host

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// HostUpdateReader is a Reader for the HostUpdate structure.
type HostUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HostUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewHostUpdateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewHostUpdateCreated creates a HostUpdateCreated with default headers values
func NewHostUpdateCreated() *HostUpdateCreated {
	return &HostUpdateCreated{}
}

/* HostUpdateCreated describes a response with status code 201, with default header values.

PATCH operation response
*/
type HostUpdateCreated struct {
	Payload *models.ConfigUpdateHostResponse
}

func (o *HostUpdateCreated) Error() string {
	return fmt.Sprintf("[PATCH /dns/host/{id}][%d] hostUpdateCreated  %+v", 201, o.Payload)
}
func (o *HostUpdateCreated) GetPayload() *models.ConfigUpdateHostResponse {
	return o.Payload
}

func (o *HostUpdateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConfigUpdateHostResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
