// Code generated by go-swagger; DO NOT EDIT.

package host

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// HostReadReader is a Reader for the HostRead structure.
type HostReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HostReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewHostReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewHostReadOK creates a HostReadOK with default headers values
func NewHostReadOK() *HostReadOK {
	return &HostReadOK{}
}

/* HostReadOK describes a response with status code 200, with default header values.

GET operation response
*/
type HostReadOK struct {
	Payload *models.ConfigReadHostResponse
}

func (o *HostReadOK) Error() string {
	return fmt.Sprintf("[GET /dns/host/{id}][%d] hostReadOK  %+v", 200, o.Payload)
}
func (o *HostReadOK) GetPayload() *models.ConfigReadHostResponse {
	return o.Payload
}

func (o *HostReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConfigReadHostResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
