// Code generated by go-swagger; DO NOT EDIT.

package fixed_address

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// FixedAddressListReader is a Reader for the FixedAddressList structure.
type FixedAddressListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *FixedAddressListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewFixedAddressListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewFixedAddressListOK creates a FixedAddressListOK with default headers values
func NewFixedAddressListOK() *FixedAddressListOK {
	return &FixedAddressListOK{}
}

/* FixedAddressListOK describes a response with status code 200, with default header values.

GET operation response
*/
type FixedAddressListOK struct {
	Payload *models.IpamsvcListFixedAddressResponse
}

func (o *FixedAddressListOK) Error() string {
	return fmt.Sprintf("[GET /dhcp/fixed_address][%d] fixedAddressListOK  %+v", 200, o.Payload)
}
func (o *FixedAddressListOK) GetPayload() *models.IpamsvcListFixedAddressResponse {
	return o.Payload
}

func (o *FixedAddressListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcListFixedAddressResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
