// Code generated by go-swagger; DO NOT EDIT.

package option_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// OptionGroupDeleteReader is a Reader for the OptionGroupDelete structure.
type OptionGroupDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OptionGroupDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewOptionGroupDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewOptionGroupDeleteNoContent creates a OptionGroupDeleteNoContent with default headers values
func NewOptionGroupDeleteNoContent() *OptionGroupDeleteNoContent {
	return &OptionGroupDeleteNoContent{}
}

/* OptionGroupDeleteNoContent describes a response with status code 204, with default header values.

No Content
*/
type OptionGroupDeleteNoContent struct {
}

func (o *OptionGroupDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /dhcp/option_group/{id}][%d] optionGroupDeleteNoContent ", 204)
}

func (o *OptionGroupDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
