// Code generated by go-swagger; DO NOT EDIT.

package view

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ViewDeleteReader is a Reader for the ViewDelete structure.
type ViewDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ViewDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewViewDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewViewDeleteNoContent creates a ViewDeleteNoContent with default headers values
func NewViewDeleteNoContent() *ViewDeleteNoContent {
	return &ViewDeleteNoContent{}
}

/* ViewDeleteNoContent describes a response with status code 204, with default header values.

No Content
*/
type ViewDeleteNoContent struct {
}

func (o *ViewDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /dns/view/{id}][%d] viewDeleteNoContent ", 204)
}

func (o *ViewDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
