// Code generated by go-swagger; DO NOT EDIT.

package view

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// ViewUpdateReader is a Reader for the ViewUpdate structure.
type ViewUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ViewUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	if response.Code() >= 400 && response.Code() < 500 {
		return nil, runtime.NewAPIError("response status code indicates client error", response, response.Code())
	}

	if response.Code() >= 500 && response.Code() < 600 {
		return nil, runtime.NewAPIError("response status code indicates server error", response, response.Code())
	}

	result := NewViewUpdateCreated()
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	return result, nil
}

// NewViewUpdateCreated creates a ViewUpdateCreated with default headers values
func NewViewUpdateCreated() *ViewUpdateCreated {
	return &ViewUpdateCreated{}
}

/* ViewUpdateCreated describes a response with status code 201, with default header values.

PATCH operation response
*/
type ViewUpdateCreated struct {
	Payload *models.ConfigUpdateViewResponse
}

func (o *ViewUpdateCreated) Error() string {
	return fmt.Sprintf("[PATCH /dns/view/{id}][%d] viewUpdateCreated  %+v", 201, o.Payload)
}
func (o *ViewUpdateCreated) GetPayload() *models.ConfigUpdateViewResponse {
	return o.Payload
}

func (o *ViewUpdateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConfigUpdateViewResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
