// Code generated by go-swagger; DO NOT EDIT.

package view

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
	b1cliruntime "github.com/infobloxopen/b1ddi-go-client/runtime"
)

// ViewBulkCopyReader is a Reader for the ViewBulkCopy structure.
type ViewBulkCopyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ViewBulkCopyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	if response.Code() >= 400 && response.Code() < 500 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates client error", response.Body(), response.Code())
	}

	if response.Code() >= 500 && response.Code() < 600 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates server error", response.Body(), response.Code())
	}

	result := NewViewBulkCopyOK()
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	return result, nil
}

// NewViewBulkCopyOK creates a ViewBulkCopyOK with default headers values
func NewViewBulkCopyOK() *ViewBulkCopyOK {
	return &ViewBulkCopyOK{}
}

/*
ViewBulkCopyOK describes a response with status code 200, with default header values.

POST operation response
*/
type ViewBulkCopyOK struct {
	Payload *models.ConfigBulkCopyResponse
}

func (o *ViewBulkCopyOK) Error() string {
	return fmt.Sprintf("[POST /dns/view/bulk_copy][%d] viewBulkCopyOK  %+v", 200, o.Payload)
}
func (o *ViewBulkCopyOK) GetPayload() *models.ConfigBulkCopyResponse {
	return o.Payload
}

func (o *ViewBulkCopyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConfigBulkCopyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
