// Code generated by go-swagger; DO NOT EDIT.

package lbdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewLbdnDeleteParams creates a new LbdnDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLbdnDeleteParams() *LbdnDeleteParams {
	return &LbdnDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLbdnDeleteParamsWithTimeout creates a new LbdnDeleteParams object
// with the ability to set a timeout on a request.
func NewLbdnDeleteParamsWithTimeout(timeout time.Duration) *LbdnDeleteParams {
	return &LbdnDeleteParams{
		timeout: timeout,
	}
}

// NewLbdnDeleteParamsWithContext creates a new LbdnDeleteParams object
// with the ability to set a context for a request.
func NewLbdnDeleteParamsWithContext(ctx context.Context) *LbdnDeleteParams {
	return &LbdnDeleteParams{
		Context: ctx,
	}
}

// NewLbdnDeleteParamsWithHTTPClient creates a new LbdnDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewLbdnDeleteParamsWithHTTPClient(client *http.Client) *LbdnDeleteParams {
	return &LbdnDeleteParams{
		HTTPClient: client,
	}
}

/*
LbdnDeleteParams contains all the parameters to send to the API endpoint

	for the lbdn delete operation.

	Typically these are written to a http.Request.
*/
type LbdnDeleteParams struct {

	/* ID.

	   An application specific resource identity of a resource
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the lbdn delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LbdnDeleteParams) WithDefaults() *LbdnDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the lbdn delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LbdnDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the lbdn delete params
func (o *LbdnDeleteParams) WithTimeout(timeout time.Duration) *LbdnDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the lbdn delete params
func (o *LbdnDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the lbdn delete params
func (o *LbdnDeleteParams) WithContext(ctx context.Context) *LbdnDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the lbdn delete params
func (o *LbdnDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the lbdn delete params
func (o *LbdnDeleteParams) WithHTTPClient(client *http.Client) *LbdnDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the lbdn delete params
func (o *LbdnDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the lbdn delete params
func (o *LbdnDeleteParams) WithID(id string) *LbdnDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the lbdn delete params
func (o *LbdnDeleteParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *LbdnDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
