// Code generated by go-swagger; DO NOT EDIT.

package lbdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
	b1cliruntime "github.com/infobloxopen/b1ddi-go-client/runtime"
)

// LbdnCreateReader is a Reader for the LbdnCreate structure.
type LbdnCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LbdnCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	if response.Code() >= 400 && response.Code() < 500 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates client error", response.Body(), response.Code())
	}

	if response.Code() >= 500 && response.Code() < 600 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates server error", response.Body(), response.Code())
	}

	result := NewLbdnCreateCreated()
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	return result, nil
}

// NewLbdnCreateCreated creates a LbdnCreateCreated with default headers values
func NewLbdnCreateCreated() *LbdnCreateCreated {
	return &LbdnCreateCreated{}
}

/*
LbdnCreateCreated describes a response with status code 201, with default header values.

POST operation response
*/
type LbdnCreateCreated struct {
	Payload *models.ConfigCreateLBDNResponse
}

func (o *LbdnCreateCreated) Error() string {
	return fmt.Sprintf("[POST /dtc/lbdn][%d] lbdnCreateCreated  %+v", 201, o.Payload)
}
func (o *LbdnCreateCreated) GetPayload() *models.ConfigCreateLBDNResponse {
	return o.Payload
}

func (o *LbdnCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConfigCreateLBDNResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
