// Code generated by go-swagger; DO NOT EDIT.

package lbdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
	b1cliruntime "github.com/infobloxopen/b1ddi-go-client/runtime"
)

// LbdnUpdateReader is a Reader for the LbdnUpdate structure.
type LbdnUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *LbdnUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	if response.Code() >= 400 && response.Code() < 500 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates client error", response.Body(), response.Code())
	}

	if response.Code() >= 500 && response.Code() < 600 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates server error", response.Body(), response.Code())
	}

	result := NewLbdnUpdateCreated()
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	return result, nil
}

// NewLbdnUpdateCreated creates a LbdnUpdateCreated with default headers values
func NewLbdnUpdateCreated() *LbdnUpdateCreated {
	return &LbdnUpdateCreated{}
}

/*
LbdnUpdateCreated describes a response with status code 201, with default header values.

PATCH operation response
*/
type LbdnUpdateCreated struct {
	Payload *models.ConfigUpdateLBDNResponse
}

func (o *LbdnUpdateCreated) Error() string {
	return fmt.Sprintf("[PATCH /dtc/lbdn/{id}][%d] lbdnUpdateCreated  %+v", 201, o.Payload)
}
func (o *LbdnUpdateCreated) GetPayload() *models.ConfigUpdateLBDNResponse {
	return o.Payload
}

func (o *LbdnUpdateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConfigUpdateLBDNResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
