// Code generated by go-swagger; DO NOT EDIT.

package lbdn

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// NewLbdnUpdateParams creates a new LbdnUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLbdnUpdateParams() *LbdnUpdateParams {
	return &LbdnUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLbdnUpdateParamsWithTimeout creates a new LbdnUpdateParams object
// with the ability to set a timeout on a request.
func NewLbdnUpdateParamsWithTimeout(timeout time.Duration) *LbdnUpdateParams {
	return &LbdnUpdateParams{
		timeout: timeout,
	}
}

// NewLbdnUpdateParamsWithContext creates a new LbdnUpdateParams object
// with the ability to set a context for a request.
func NewLbdnUpdateParamsWithContext(ctx context.Context) *LbdnUpdateParams {
	return &LbdnUpdateParams{
		Context: ctx,
	}
}

// NewLbdnUpdateParamsWithHTTPClient creates a new LbdnUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewLbdnUpdateParamsWithHTTPClient(client *http.Client) *LbdnUpdateParams {
	return &LbdnUpdateParams{
		HTTPClient: client,
	}
}

/*
LbdnUpdateParams contains all the parameters to send to the API endpoint

	for the lbdn update operation.

	Typically these are written to a http.Request.
*/
type LbdnUpdateParams struct {

	// Body.
	Body *models.ConfigLBDN

	/* ID.

	   An application specific resource identity of a resource
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the lbdn update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LbdnUpdateParams) WithDefaults() *LbdnUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the lbdn update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LbdnUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the lbdn update params
func (o *LbdnUpdateParams) WithTimeout(timeout time.Duration) *LbdnUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the lbdn update params
func (o *LbdnUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the lbdn update params
func (o *LbdnUpdateParams) WithContext(ctx context.Context) *LbdnUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the lbdn update params
func (o *LbdnUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the lbdn update params
func (o *LbdnUpdateParams) WithHTTPClient(client *http.Client) *LbdnUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the lbdn update params
func (o *LbdnUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the lbdn update params
func (o *LbdnUpdateParams) WithBody(body *models.ConfigLBDN) *LbdnUpdateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the lbdn update params
func (o *LbdnUpdateParams) SetBody(body *models.ConfigLBDN) {
	o.Body = body
}

// WithID adds the id to the lbdn update params
func (o *LbdnUpdateParams) WithID(id string) *LbdnUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the lbdn update params
func (o *LbdnUpdateParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *LbdnUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
