// Code generated by go-swagger; DO NOT EDIT.

package auth_zone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// AuthZoneReadReader is a Reader for the AuthZoneRead structure.
type AuthZoneReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AuthZoneReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAuthZoneReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAuthZoneReadOK creates a AuthZoneReadOK with default headers values
func NewAuthZoneReadOK() *AuthZoneReadOK {
	return &AuthZoneReadOK{}
}

/* AuthZoneReadOK describes a response with status code 200, with default header values.

GET operation response
*/
type AuthZoneReadOK struct {
	Payload *models.ConfigReadAuthZoneResponse
}

func (o *AuthZoneReadOK) Error() string {
	return fmt.Sprintf("[GET /dns/auth_zone/{id}][%d] authZoneReadOK  %+v", 200, o.Payload)
}
func (o *AuthZoneReadOK) GetPayload() *models.ConfigReadAuthZoneResponse {
	return o.Payload
}

func (o *AuthZoneReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConfigReadAuthZoneResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
