// Code generated by go-swagger; DO NOT EDIT.

package auth_zone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AuthZoneDeleteReader is a Reader for the AuthZoneDelete structure.
type AuthZoneDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AuthZoneDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewAuthZoneDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAuthZoneDeleteNoContent creates a AuthZoneDeleteNoContent with default headers values
func NewAuthZoneDeleteNoContent() *AuthZoneDeleteNoContent {
	return &AuthZoneDeleteNoContent{}
}

/* AuthZoneDeleteNoContent describes a response with status code 204, with default header values.

No Content
*/
type AuthZoneDeleteNoContent struct {
}

func (o *AuthZoneDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /dns/auth_zone/{id}][%d] authZoneDeleteNoContent ", 204)
}

func (o *AuthZoneDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
