// Code generated by go-swagger; DO NOT EDIT.

package auth_zone

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
	b1cliruntime "github.com/infobloxopen/b1ddi-go-client/runtime"
)

// AuthZoneUpdateReader is a Reader for the AuthZoneUpdate structure.
type AuthZoneUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AuthZoneUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	if response.Code() >= 400 && response.Code() < 500 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates client error", response.Body(), response.Code())
	}

	if response.Code() >= 500 && response.Code() < 600 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates server error", response.Body(), response.Code())
	}

	result := NewAuthZoneUpdateOK()
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	return result, nil
}

// NewAuthZoneUpdateOK creates a AuthZoneUpdateOK with default headers values
func NewAuthZoneUpdateOK() *AuthZoneUpdateOK {
	return &AuthZoneUpdateOK{}
}

/*
AuthZoneUpdateOK describes a response with status code 200, with default header values.

PATCH operation response
*/
type AuthZoneUpdateOK struct {
	Payload *models.ConfigUpdateAuthZoneResponse
}

func (o *AuthZoneUpdateOK) Error() string {
	return fmt.Sprintf("[PATCH /dns/auth_zone/{id}][%d] authZoneUpdateOK  %+v", 200, o.Payload)
}
func (o *AuthZoneUpdateOK) GetPayload() *models.ConfigUpdateAuthZoneResponse {
	return o.Payload
}

func (o *AuthZoneUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConfigUpdateAuthZoneResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
