// Code generated by go-swagger; DO NOT EDIT.

package address_block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAddressBlockCreateNextAvailableSubnetParams creates a new AddressBlockCreateNextAvailableSubnetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddressBlockCreateNextAvailableSubnetParams() *AddressBlockCreateNextAvailableSubnetParams {
	return &AddressBlockCreateNextAvailableSubnetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddressBlockCreateNextAvailableSubnetParamsWithTimeout creates a new AddressBlockCreateNextAvailableSubnetParams object
// with the ability to set a timeout on a request.
func NewAddressBlockCreateNextAvailableSubnetParamsWithTimeout(timeout time.Duration) *AddressBlockCreateNextAvailableSubnetParams {
	return &AddressBlockCreateNextAvailableSubnetParams{
		timeout: timeout,
	}
}

// NewAddressBlockCreateNextAvailableSubnetParamsWithContext creates a new AddressBlockCreateNextAvailableSubnetParams object
// with the ability to set a context for a request.
func NewAddressBlockCreateNextAvailableSubnetParamsWithContext(ctx context.Context) *AddressBlockCreateNextAvailableSubnetParams {
	return &AddressBlockCreateNextAvailableSubnetParams{
		Context: ctx,
	}
}

// NewAddressBlockCreateNextAvailableSubnetParamsWithHTTPClient creates a new AddressBlockCreateNextAvailableSubnetParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddressBlockCreateNextAvailableSubnetParamsWithHTTPClient(client *http.Client) *AddressBlockCreateNextAvailableSubnetParams {
	return &AddressBlockCreateNextAvailableSubnetParams{
		HTTPClient: client,
	}
}

/*
AddressBlockCreateNextAvailableSubnetParams contains all the parameters to send to the API endpoint

	for the address block create next available subnet operation.

	Typically these are written to a http.Request.
*/
type AddressBlockCreateNextAvailableSubnetParams struct {

	/* ID.

	   An application specific resource identity of a resource
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the address block create next available subnet params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddressBlockCreateNextAvailableSubnetParams) WithDefaults() *AddressBlockCreateNextAvailableSubnetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the address block create next available subnet params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddressBlockCreateNextAvailableSubnetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the address block create next available subnet params
func (o *AddressBlockCreateNextAvailableSubnetParams) WithTimeout(timeout time.Duration) *AddressBlockCreateNextAvailableSubnetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the address block create next available subnet params
func (o *AddressBlockCreateNextAvailableSubnetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the address block create next available subnet params
func (o *AddressBlockCreateNextAvailableSubnetParams) WithContext(ctx context.Context) *AddressBlockCreateNextAvailableSubnetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the address block create next available subnet params
func (o *AddressBlockCreateNextAvailableSubnetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the address block create next available subnet params
func (o *AddressBlockCreateNextAvailableSubnetParams) WithHTTPClient(client *http.Client) *AddressBlockCreateNextAvailableSubnetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the address block create next available subnet params
func (o *AddressBlockCreateNextAvailableSubnetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the address block create next available subnet params
func (o *AddressBlockCreateNextAvailableSubnetParams) WithID(id string) *AddressBlockCreateNextAvailableSubnetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the address block create next available subnet params
func (o *AddressBlockCreateNextAvailableSubnetParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *AddressBlockCreateNextAvailableSubnetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
