// Code generated by go-swagger; DO NOT EDIT.

package address_block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AddressBlockDeleteReader is a Reader for the AddressBlockDelete structure.
type AddressBlockDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddressBlockDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewAddressBlockDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddressBlockDeleteNoContent creates a AddressBlockDeleteNoContent with default headers values
func NewAddressBlockDeleteNoContent() *AddressBlockDeleteNoContent {
	return &AddressBlockDeleteNoContent{}
}

/* AddressBlockDeleteNoContent describes a response with status code 204, with default header values.

No Content
*/
type AddressBlockDeleteNoContent struct {
}

func (o *AddressBlockDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /ipam/address_block/{id}][%d] addressBlockDeleteNoContent ", 204)
}

func (o *AddressBlockDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
