// Code generated by go-swagger; DO NOT EDIT.

package address_block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// AddressBlockListNextAvailableSubnetReader is a Reader for the AddressBlockListNextAvailableSubnet structure.
type AddressBlockListNextAvailableSubnetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddressBlockListNextAvailableSubnetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddressBlockListNextAvailableSubnetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddressBlockListNextAvailableSubnetOK creates a AddressBlockListNextAvailableSubnetOK with default headers values
func NewAddressBlockListNextAvailableSubnetOK() *AddressBlockListNextAvailableSubnetOK {
	return &AddressBlockListNextAvailableSubnetOK{}
}

/* AddressBlockListNextAvailableSubnetOK describes a response with status code 200, with default header values.

GET operation response
*/
type AddressBlockListNextAvailableSubnetOK struct {
	Payload *models.IpamsvcNextAvailableSubnetResponse
}

func (o *AddressBlockListNextAvailableSubnetOK) Error() string {
	return fmt.Sprintf("[GET /ipam/address_block/{id}/nextavailablesubnet][%d] addressBlockListNextAvailableSubnetOK  %+v", 200, o.Payload)
}
func (o *AddressBlockListNextAvailableSubnetOK) GetPayload() *models.IpamsvcNextAvailableSubnetResponse {
	return o.Payload
}

func (o *AddressBlockListNextAvailableSubnetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcNextAvailableSubnetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
