// Code generated by go-swagger; DO NOT EDIT.

package address_block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// AddressBlockListNextAvailableABReader is a Reader for the AddressBlockListNextAvailableAB structure.
type AddressBlockListNextAvailableABReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddressBlockListNextAvailableABReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddressBlockListNextAvailableABOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddressBlockListNextAvailableABOK creates a AddressBlockListNextAvailableABOK with default headers values
func NewAddressBlockListNextAvailableABOK() *AddressBlockListNextAvailableABOK {
	return &AddressBlockListNextAvailableABOK{}
}

/* AddressBlockListNextAvailableABOK describes a response with status code 200, with default header values.

GET operation response
*/
type AddressBlockListNextAvailableABOK struct {
	Payload *models.IpamsvcNextAvailableABResponse
}

func (o *AddressBlockListNextAvailableABOK) Error() string {
	return fmt.Sprintf("[GET /ipam/address_block/{id}/nextavailableaddressblock][%d] addressBlockListNextAvailableABOK  %+v", 200, o.Payload)
}
func (o *AddressBlockListNextAvailableABOK) GetPayload() *models.IpamsvcNextAvailableABResponse {
	return o.Payload
}

func (o *AddressBlockListNextAvailableABOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcNextAvailableABResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
