// Code generated by go-swagger; DO NOT EDIT.

package address_block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// AddressBlockCopyReader is a Reader for the AddressBlockCopy structure.
type AddressBlockCopyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddressBlockCopyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewAddressBlockCopyCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddressBlockCopyCreated creates a AddressBlockCopyCreated with default headers values
func NewAddressBlockCopyCreated() *AddressBlockCopyCreated {
	return &AddressBlockCopyCreated{}
}

/* AddressBlockCopyCreated describes a response with status code 201, with default header values.

POST operation response
*/
type AddressBlockCopyCreated struct {
	Payload *models.IpamsvcCopyAddressBlockResponse
}

func (o *AddressBlockCopyCreated) Error() string {
	return fmt.Sprintf("[POST /ipam/address_block/{id}/copy][%d] addressBlockCopyCreated  %+v", 201, o.Payload)
}
func (o *AddressBlockCopyCreated) GetPayload() *models.IpamsvcCopyAddressBlockResponse {
	return o.Payload
}

func (o *AddressBlockCopyCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcCopyAddressBlockResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
