// Code generated by go-swagger; DO NOT EDIT.

package address_block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/infobloxopen/b1ddi-go-client/models"
)

// AddressBlockUpdateReader is a Reader for the AddressBlockUpdate structure.
type AddressBlockUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddressBlockUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewAddressBlockUpdateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddressBlockUpdateCreated creates a AddressBlockUpdateCreated with default headers values
func NewAddressBlockUpdateCreated() *AddressBlockUpdateCreated {
	return &AddressBlockUpdateCreated{}
}

/* AddressBlockUpdateCreated describes a response with status code 201, with default header values.

PATCH operation response
*/
type AddressBlockUpdateCreated struct {
	Payload *models.IpamsvcUpdateAddressBlockResponse
}

func (o *AddressBlockUpdateCreated) Error() string {
	return fmt.Sprintf("[PATCH /ipam/address_block/{id}][%d] addressBlockUpdateCreated  %+v", 201, o.Payload)
}
func (o *AddressBlockUpdateCreated) GetPayload() *models.IpamsvcUpdateAddressBlockResponse {
	return o.Payload
}

func (o *AddressBlockUpdateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.IpamsvcUpdateAddressBlockResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
