// Code generated by go-swagger; DO NOT EDIT.

package address_block

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	b1cliruntime "github.com/infobloxopen/b1ddi-go-client/runtime"
)

// AddressBlockDeleteReader is a Reader for the AddressBlockDelete structure.
type AddressBlockDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddressBlockDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	if response.Code() >= 400 && response.Code() < 500 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates client error", response.Body(), response.Code())
	}

	if response.Code() >= 500 && response.Code() < 600 {
		return nil, b1cliruntime.NewAPIHTTPError("response status code indicates server error", response.Body(), response.Code())
	}

	result := NewAddressBlockDeleteOK()
	if err := result.readResponse(response, consumer, o.formats); err != nil {
		return nil, err
	}
	return result, nil
}

// NewAddressBlockDeleteOK creates a AddressBlockDeleteOK with default headers values
func NewAddressBlockDeleteOK() *AddressBlockDeleteOK {
	return &AddressBlockDeleteOK{}
}

/*
AddressBlockDeleteOK describes a response with status code 200, with default header values.

OK
*/
type AddressBlockDeleteOK struct {
}

func (o *AddressBlockDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /ipam/address_block/{id}][%d] addressBlockDeleteOK ", 200)
}

func (o *AddressBlockDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
