// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AuthZoneExternalProvider ExternalProvider
//
// The external provider object.
//
// swagger:model AuthZoneExternalProvider
type AuthZoneExternalProvider struct {

	// The identifier of the external provider.
	// Read Only: true
	ID string `json:"id,omitempty"`

	// The name of the external provider.
	Name string `json:"name,omitempty"`

	// Defines the type of external provider.
	// Allowed values:
	//  * _bloxone_ddi_: host type is BloxOne DDI,
	//  * _microsoft_azure_: host type is Microsoft Azure,
	//  * _amazon_web_service_: host type is Amazon Web Services,
	//  * _microsoft_active_directory_: host type is Microsoft Active Directory,
	//  * _google_cloud_platform_: host type is Google Cloud Platform.
	Type string `json:"type,omitempty"`
}

// Validate validates this auth zone external provider
func (m *AuthZoneExternalProvider) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this auth zone external provider based on the context it is used
func (m *AuthZoneExternalProvider) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AuthZoneExternalProvider) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", string(m.ID)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AuthZoneExternalProvider) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthZoneExternalProvider) UnmarshalBinary(b []byte) error {
	var res AuthZoneExternalProvider
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
