// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ConfigDTCPolicy DTCPolicy
//
// The __DTC Policy__ object.
//
// swagger:model configDTCPolicy
type ConfigDTCPolicy struct {

	// __DTC Policy__ display name.
	// Read Only: true
	Name string `json:"name,omitempty"`

	// The resource identifier.
	PolicyID string `json:"policy_id,omitempty"`
}

// Validate validates this config d t c policy
func (m *ConfigDTCPolicy) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this config d t c policy based on the context it is used
func (m *ConfigDTCPolicy) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateName(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConfigDTCPolicy) contextValidateName(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "name", "body", string(m.Name)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConfigDTCPolicy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfigDTCPolicy) UnmarshalBinary(b []byte) error {
	var res ConfigDTCPolicy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
