// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ConfigBulkCopyError config bulk copy error
//
// swagger:model configBulkCopyError
type ConfigBulkCopyError struct {

	// The description of the resource that was requested to be copied.
	Description string `json:"description,omitempty"`

	// The resource identifier.
	// Read Only: true
	ID string `json:"id,omitempty"`

	// The reason why the copy failed.
	Message string `json:"message,omitempty"`
}

// Validate validates this config bulk copy error
func (m *ConfigBulkCopyError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validate this config bulk copy error based on the context it is used
func (m *ConfigBulkCopyError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConfigBulkCopyError) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", string(m.ID)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ConfigBulkCopyError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfigBulkCopyError) UnmarshalBinary(b []byte) error {
	var res ConfigBulkCopyError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
