// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConfigWarning Warning
//
// Warning message related to the containing object.
//
// swagger:model configWarning
type ConfigWarning struct {

	// Warning message.
	Message string `json:"message,omitempty"`

	// Name of a warning.
	Name string `json:"name,omitempty"`
}

// Validate validates this config warning
func (m *ConfigWarning) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this config warning based on context it is used
func (m *ConfigWarning) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConfigWarning) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfigWarning) UnmarshalBinary(b []byte) error {
	var res ConfigWarning
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
