// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IpamsvcGlobal Global
//
// The global DHCP configuration (_dhcp/global_). Used by default unless more specific configuration exists. There is only one instance of this object.
//
// swagger:model ipamsvcGlobal
type IpamsvcGlobal struct {

	// The global Automated Scope Management configuration.
	AsmConfig *IpamsvcASMConfig `json:"asm_config,omitempty"`

	// The Kerberos principal name. It uses the typical Kerberos notation: <SERVICE-NAME>/<server-domain-name>@<REALM>.
	//
	// Defaults to empty.
	ClientPrincipal string `json:"client_principal,omitempty"`

	// The global configuration to control who does the DDNS updates.
	//
	// Valid values are:
	// * _client_: DHCP server updates DNS if requested by client.
	// * _server_: DHCP server always updates DNS, overriding an update request from the client, unless the client requests no updates.
	// * _ignore_: DHCP server always updates DNS, even if the client says not to.
	// * _over_client_update_: Same as _server_. DHCP server always updates DNS, overriding an update request from the client, unless the client requests no updates.
	// * _over_no_update_: DHCP server updates DNS even if the client requests that no updates be done. If the client requests to do the update, DHCP server allows it.
	//
	// Defaults to _client_.
	DdnsClientUpdate string `json:"ddns_client_update,omitempty"`

	// The mode used for resolving conflicts while performing DDNS updates.
	//
	// Valid values are:
	// * _check_with_dhcid_: It includes adding a DHCID record and checking that record via conflict detection as per RFC 4703.
	// * _no_check_with_dhcid_: This will ignore conflict detection but add a DHCID record when creating/updating an entry.
	// * _check_exists_with_dhcid_: This will check if there is an existing DHCID record but does not verify the value of the record matches the update. This will also update the DHCID record for the entry.
	// * _no_check_without_dhcid_: This ignores conflict detection and will not add a DHCID record when creating/updating a DDNS entry.
	//
	// Defaults to _check_with_dhcid_.
	DdnsConflictResolutionMode string `json:"ddns_conflict_resolution_mode,omitempty"`

	// The domain suffix for DDNS updates. FQDN, may be empty.
	//
	// Must be specified if _ddns_enabled_ is _true_.
	//
	// Defaults to empty.
	DdnsDomain string `json:"ddns_domain,omitempty"`

	// Indicates if DDNS updates should be performed for leases.
	//
	// All other ddns_* configuration fields are ignored when this flag is unset.
	//
	// At a minimum, _ddns_domain_ and _ddns_zones_ must be configured to enable DDNS.
	//
	// Defaults to _false_.
	DdnsEnabled bool `json:"ddns_enabled,omitempty"`

	// Indicates if DDNS needs to generate a hostname when not supplied by the client.
	//
	// Defaults to _false_.
	DdnsGenerateName bool `json:"ddns_generate_name,omitempty"`

	// The prefix used in the generation of an FQDN.
	//
	// When generating a name, DHCP server will construct the name in the format: [ddns-generated-prefix]-[address-text].[ddns-qualifying-suffix].
	// where address-text is simply the lease IP address converted to a hyphenated string.
	//
	// Defaults to "myhost".
	DdnsGeneratedPrefix string `json:"ddns_generated_prefix,omitempty"`

	// Determines if DDNS updates are enabled at the global level.
	// Defaults to _true_.
	DdnsSendUpdates bool `json:"ddns_send_updates,omitempty"`

	// DDNS TTL value - to be calculated as a simple percentage of the lease's lifetime, using the parameter's value as the percentage.
	// It is specified as a percentage (e.g. 25, 75).
	// Defaults to unspecified.
	DdnsTTLPercent float32 `json:"ddns_ttl_percent,omitempty"`

	// Instructs the DHCP server to always update the DNS information when a lease is renewed even if its DNS information has not changed.
	//
	// Defaults to _false_.
	DdnsUpdateOnRenew bool `json:"ddns_update_on_renew,omitempty"`

	// When true, DHCP server will apply conflict resolution, as described in RFC 4703, when attempting to fulfill the update request.
	//
	// When false, DHCP server will simply attempt to update the DNS entries per the request, regardless of whether or not they conflict with existing entries owned by other DHCP4 clients.
	//
	// Defaults to _true_.
	DdnsUseConflictResolution bool `json:"ddns_use_conflict_resolution,omitempty"`

	// DNS zones that DDNS updates can be sent to.
	// There is no resolver fallback. The target zone must be explicitly configured for the update to be performed.
	//
	// Updates are sent to the closest enclosing zone.
	//
	// Error if _ddns_enabled_ is _true_ and the _ddns_domain_ does not have a corresponding entry in _ddns_zones_.
	//
	// Error if there are items with duplicate zone in the list.
	//
	// Defaults to empty list.
	DdnsZones []*IpamsvcDDNSZone `json:"ddns_zones,omitempty"`

	// The global DHCP configuration that controls how leases are issued.
	DhcpConfig *IpamsvcDHCPConfig `json:"dhcp_config,omitempty"`

	// The list of DHCP options or group of options for IPv4.
	// An option list is ordered and may include both option groups and specific options.
	// Multiple occurrences of the same option or group is not an error.
	// The last occurrence of an option in the list will be used.
	//
	// Error if the graph of referenced groups contains cycles.
	//
	// Defaults to empty list.
	DhcpOptions []*IpamsvcOptionItem `json:"dhcp_options,omitempty"`

	// The list of DHCP options or group of options for IPv6.
	// An option list is ordered and may include both option groups and specific options.
	// Multiple occurrences of the same option or group is not an error.
	// The last occurrence of an option in the list will be used.
	//
	// Error if the graph of referenced groups contains cycles.
	//
	// Defaults to empty list.
	DhcpOptionsV6 []*IpamsvcOptionItem `json:"dhcp_options_v6,omitempty"`

	// The global DHCP Utilization threshold settings.
	DhcpThreshold *IpamsvcDHCPUtilizationThreshold `json:"dhcp_threshold,omitempty"`

	// The behavior when GSS-TSIG should be used (a matching external DNS server is configured) but no GSS-TSIG key is available.
	// If configured to _false_ (the default) this DNS server is skipped, if configured to _true_ the DNS server is ignored
	// and the DNS update is sent with the configured DHCP-DDNS protection e.g. TSIG key or without any protection when
	// none was configured.
	//
	// Defaults to _false_.
	GssTsigFallback bool `json:"gss_tsig_fallback,omitempty"`

	// The configuration for header option filename field.
	HeaderOptionFilename string `json:"header_option_filename,omitempty"`

	// The configuration for header option server address field.
	HeaderOptionServerAddress string `json:"header_option_server_address,omitempty"`

	// The configuration for header option server name field.
	HeaderOptionServerName string `json:"header_option_server_name,omitempty"`

	// The character to replace non-matching characters with, when hostname rewrite is enabled in global configuration.
	//
	// Any single ASCII character or no character if the invalid characters should be removed without replacement.
	//
	// Defaults to "-".
	HostnameRewriteChar string `json:"hostname_rewrite_char,omitempty"`

	// The global configuration to indicate if the hostnames supplied by the client will be rewritten prior to DDNS update by replacing every character that does not match _hostname_rewrite_regex_ by _hostname_rewrite_char_.
	//
	// Defaults to _false_.
	HostnameRewriteEnabled bool `json:"hostname_rewrite_enabled,omitempty"`

	// The regex bracket expression to match valid characters when hostname rewrite is enabled in global configuration.
	//
	// Must begin with "[" and end with "]" and be a compilable POSIX regex.
	//
	// Defaults to "[^a-zA-Z0-9_.]".
	HostnameRewriteRegex string `json:"hostname_rewrite_regex,omitempty"`

	// The resource identifier.
	// Read Only: true
	ID string `json:"id,omitempty"`

	// Address of Kerberos Key Distribution Center.
	//
	// Defaults to empty.
	KerberosKdc string `json:"kerberos_kdc,omitempty"`

	// _kerberos_keys_ contains a list of keys for GSS-TSIG signed dynamic updates.
	//
	// Defaults to empty.
	KerberosKeys []*IpamsvcKerberosKey `json:"kerberos_keys"`

	// Time interval (in seconds) the keys for each configured external DNS server are checked for rekeying,
	// i.e. a new key is created to replace the current usable one when its age is greater than the _kerberos_rekey_interval_ value.
	//
	// Defaults to 120 seconds.
	KerberosRekeyInterval int64 `json:"kerberos_rekey_interval,omitempty"`

	// Time interval (in seconds) to retry to create a key if any error occurred previously for any configured external DNS server.
	//
	// Defaults to 30 seconds.
	KerberosRetryInterval int64 `json:"kerberos_retry_interval,omitempty"`

	// Lifetime (in seconds) of GSS-TSIG keys in the TKEY protocol.
	//
	// Defaults to 160 seconds.
	KerberosTkeyLifetime int64 `json:"kerberos_tkey_lifetime,omitempty"`

	// Determines which protocol is used to establish the security context with the external DNS servers, TCP or UDP.
	//
	// Defaults to _tcp_.
	KerberosTkeyProtocol string `json:"kerberos_tkey_protocol,omitempty"`

	// When enabled, DHCP Server will prefer option 12 over option 81 in the incoming client request.
	//
	// Defaults to _false_.
	PreferOption12 bool `json:"prefer_option_12,omitempty"`

	// When enabled, DHCP Server will remove the suffix from the option 81 in the incoming client request.
	//
	// Defaults to _false_.
	RemoveSuffixOption81 bool `json:"remove_suffix_option_81,omitempty"`

	// The Kerberos principal name of the external DNS server that will receive updates.
	//
	// Defaults to empty.
	ServerPrincipal string `json:"server_principal,omitempty"`

	// The resource identifier.
	VendorSpecificOptionOptionSpace string `json:"vendor_specific_option_option_space,omitempty"`
}

// Validate validates this ipamsvc global
func (m *IpamsvcGlobal) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAsmConfig(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDdnsZones(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDhcpConfig(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDhcpOptions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDhcpOptionsV6(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDhcpThreshold(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKerberosKeys(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IpamsvcGlobal) validateAsmConfig(formats strfmt.Registry) error {
	if swag.IsZero(m.AsmConfig) { // not required
		return nil
	}

	if m.AsmConfig != nil {
		if err := m.AsmConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("asm_config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("asm_config")
			}
			return err
		}
	}

	return nil
}

func (m *IpamsvcGlobal) validateDdnsZones(formats strfmt.Registry) error {
	if swag.IsZero(m.DdnsZones) { // not required
		return nil
	}

	for i := 0; i < len(m.DdnsZones); i++ {
		if swag.IsZero(m.DdnsZones[i]) { // not required
			continue
		}

		if m.DdnsZones[i] != nil {
			if err := m.DdnsZones[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("ddns_zones" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("ddns_zones" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *IpamsvcGlobal) validateDhcpConfig(formats strfmt.Registry) error {
	if swag.IsZero(m.DhcpConfig) { // not required
		return nil
	}

	if m.DhcpConfig != nil {
		if err := m.DhcpConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("dhcp_config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("dhcp_config")
			}
			return err
		}
	}

	return nil
}

func (m *IpamsvcGlobal) validateDhcpOptions(formats strfmt.Registry) error {
	if swag.IsZero(m.DhcpOptions) { // not required
		return nil
	}

	for i := 0; i < len(m.DhcpOptions); i++ {
		if swag.IsZero(m.DhcpOptions[i]) { // not required
			continue
		}

		if m.DhcpOptions[i] != nil {
			if err := m.DhcpOptions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("dhcp_options" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("dhcp_options" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *IpamsvcGlobal) validateDhcpOptionsV6(formats strfmt.Registry) error {
	if swag.IsZero(m.DhcpOptionsV6) { // not required
		return nil
	}

	for i := 0; i < len(m.DhcpOptionsV6); i++ {
		if swag.IsZero(m.DhcpOptionsV6[i]) { // not required
			continue
		}

		if m.DhcpOptionsV6[i] != nil {
			if err := m.DhcpOptionsV6[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("dhcp_options_v6" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("dhcp_options_v6" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *IpamsvcGlobal) validateDhcpThreshold(formats strfmt.Registry) error {
	if swag.IsZero(m.DhcpThreshold) { // not required
		return nil
	}

	if m.DhcpThreshold != nil {
		if err := m.DhcpThreshold.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("dhcp_threshold")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("dhcp_threshold")
			}
			return err
		}
	}

	return nil
}

func (m *IpamsvcGlobal) validateKerberosKeys(formats strfmt.Registry) error {
	if swag.IsZero(m.KerberosKeys) { // not required
		return nil
	}

	for i := 0; i < len(m.KerberosKeys); i++ {
		if swag.IsZero(m.KerberosKeys[i]) { // not required
			continue
		}

		if m.KerberosKeys[i] != nil {
			if err := m.KerberosKeys[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("kerberos_keys" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("kerberos_keys" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this ipamsvc global based on the context it is used
func (m *IpamsvcGlobal) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAsmConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDdnsZones(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDhcpConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDhcpOptions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDhcpOptionsV6(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateDhcpThreshold(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateKerberosKeys(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IpamsvcGlobal) contextValidateAsmConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.AsmConfig != nil {

		if swag.IsZero(m.AsmConfig) { // not required
			return nil
		}

		if err := m.AsmConfig.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("asm_config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("asm_config")
			}
			return err
		}
	}

	return nil
}

func (m *IpamsvcGlobal) contextValidateDdnsZones(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.DdnsZones); i++ {

		if m.DdnsZones[i] != nil {

			if swag.IsZero(m.DdnsZones[i]) { // not required
				return nil
			}

			if err := m.DdnsZones[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("ddns_zones" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("ddns_zones" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *IpamsvcGlobal) contextValidateDhcpConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.DhcpConfig != nil {

		if swag.IsZero(m.DhcpConfig) { // not required
			return nil
		}

		if err := m.DhcpConfig.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("dhcp_config")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("dhcp_config")
			}
			return err
		}
	}

	return nil
}

func (m *IpamsvcGlobal) contextValidateDhcpOptions(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.DhcpOptions); i++ {

		if m.DhcpOptions[i] != nil {

			if swag.IsZero(m.DhcpOptions[i]) { // not required
				return nil
			}

			if err := m.DhcpOptions[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("dhcp_options" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("dhcp_options" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *IpamsvcGlobal) contextValidateDhcpOptionsV6(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.DhcpOptionsV6); i++ {

		if m.DhcpOptionsV6[i] != nil {

			if swag.IsZero(m.DhcpOptionsV6[i]) { // not required
				return nil
			}

			if err := m.DhcpOptionsV6[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("dhcp_options_v6" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("dhcp_options_v6" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *IpamsvcGlobal) contextValidateDhcpThreshold(ctx context.Context, formats strfmt.Registry) error {

	if m.DhcpThreshold != nil {

		if swag.IsZero(m.DhcpThreshold) { // not required
			return nil
		}

		if err := m.DhcpThreshold.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("dhcp_threshold")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("dhcp_threshold")
			}
			return err
		}
	}

	return nil
}

func (m *IpamsvcGlobal) contextValidateID(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "id", "body", string(m.ID)); err != nil {
		return err
	}

	return nil
}

func (m *IpamsvcGlobal) contextValidateKerberosKeys(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.KerberosKeys); i++ {

		if m.KerberosKeys[i] != nil {

			if swag.IsZero(m.KerberosKeys[i]) { // not required
				return nil
			}

			if err := m.KerberosKeys[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("kerberos_keys" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("kerberos_keys" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *IpamsvcGlobal) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IpamsvcGlobal) UnmarshalBinary(b []byte) error {
	var res IpamsvcGlobal
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
