// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IpamsvcCreateLeasesCommandResponse CreateLeasesCommandResponse
//
// The response format to perform leases command.
//
// swagger:model ipamsvcCreateLeasesCommandResponse
type IpamsvcCreateLeasesCommandResponse struct {

	// success
	Success string `json:"success,omitempty"`
}

// Validate validates this ipamsvc create leases command response
func (m *IpamsvcCreateLeasesCommandResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ipamsvc create leases command response based on context it is used
func (m *IpamsvcCreateLeasesCommandResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IpamsvcCreateLeasesCommandResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IpamsvcCreateLeasesCommandResponse) UnmarshalBinary(b []byte) error {
	var res IpamsvcCreateLeasesCommandResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
