// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IpamsvcAccessFilter AccessFilter
//
// The __AccessFilter__ object represents an allow/deny filter for a DHCP range.
//
// swagger:model ipamsvcAccessFilter
type IpamsvcAccessFilter struct {

	// The access type of DHCP filter (_allow_ or _deny_).
	//
	// Defaults to _allow_.
	// Required: true
	Access *string `json:"access"`

	// The resource identifier.
	HardwareFilterID string `json:"hardware_filter_id,omitempty"`

	// The resource identifier.
	OptionFilterID string `json:"option_filter_id,omitempty"`
}

// Validate validates this ipamsvc access filter
func (m *IpamsvcAccessFilter) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccess(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IpamsvcAccessFilter) validateAccess(formats strfmt.Registry) error {

	if err := validate.Required("access", "body", m.Access); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this ipamsvc access filter based on context it is used
func (m *IpamsvcAccessFilter) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IpamsvcAccessFilter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IpamsvcAccessFilter) UnmarshalBinary(b []byte) error {
	var res IpamsvcAccessFilter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
