// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IpamsvcHAGroupHost HAGroupHost
//
// An __HAGroupHost__ object (_dhcp/ha_group_host_) represents an on-prem host belonging to an HA Group.
//
// swagger:model ipamsvcHAGroupHost
type IpamsvcHAGroupHost struct {

	// The address on which this host listens.
	Address string `json:"address,omitempty"`

	// Last successful heartbeat received from its peer/s. This field is set when the _collect_stats_ is set to _true_ in the _GET_ _/dhcp/ha_group_ request.
	Heartbeats []*IpamsvcHAGroupHeartbeats `json:"heartbeats"`

	// The resource identifier.
	// Required: true
	Host *string `json:"host"`

	// The HA port.
	// Read Only: true
	Port int64 `json:"port,omitempty"`

	// The role of this host in the HA relationship: _active_ or _passive_.
	Role string `json:"role,omitempty"`

	// The state of DHCP on the host. This field is set when the _collect_stats_ is set to _true_ in the _GET_ _/dhcp/ha_group_ request.
	State string `json:"state,omitempty"`
}

// Validate validates this ipamsvc h a group host
func (m *IpamsvcHAGroupHost) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHeartbeats(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHost(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IpamsvcHAGroupHost) validateHeartbeats(formats strfmt.Registry) error {
	if swag.IsZero(m.Heartbeats) { // not required
		return nil
	}

	for i := 0; i < len(m.Heartbeats); i++ {
		if swag.IsZero(m.Heartbeats[i]) { // not required
			continue
		}

		if m.Heartbeats[i] != nil {
			if err := m.Heartbeats[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("heartbeats" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("heartbeats" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *IpamsvcHAGroupHost) validateHost(formats strfmt.Registry) error {

	if err := validate.Required("host", "body", m.Host); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this ipamsvc h a group host based on the context it is used
func (m *IpamsvcHAGroupHost) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateHeartbeats(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePort(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IpamsvcHAGroupHost) contextValidateHeartbeats(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Heartbeats); i++ {

		if m.Heartbeats[i] != nil {

			if swag.IsZero(m.Heartbeats[i]) { // not required
				return nil
			}

			if err := m.Heartbeats[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("heartbeats" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("heartbeats" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *IpamsvcHAGroupHost) contextValidatePort(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "port", "body", int64(m.Port)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *IpamsvcHAGroupHost) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IpamsvcHAGroupHost) UnmarshalBinary(b []byte) error {
	var res IpamsvcHAGroupHost
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
