// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IpamsvcLeaseAddress ipamsvc lease address
//
// swagger:model ipamsvcLeaseAddress
type IpamsvcLeaseAddress struct {

	// The IP address for the DHCP lease in IPv4 or IPv6 format within the IP space specified by _space_ field.
	Address string `json:"address,omitempty"`

	// The resource identifier.
	Space string `json:"space,omitempty"`
}

// Validate validates this ipamsvc lease address
func (m *IpamsvcLeaseAddress) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this ipamsvc lease address based on context it is used
func (m *IpamsvcLeaseAddress) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IpamsvcLeaseAddress) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IpamsvcLeaseAddress) UnmarshalBinary(b []byte) error {
	var res IpamsvcLeaseAddress
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
